In [ ]:
import numpy as mp
import pandas as pd

In [ ]:
subs=pd.read_csv("/content/subs.csv")

In [ ]:
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [ ]:
subs.head()

   Subscribers gained
0                  48
1                  57
2                  40
3                  43
4                  44

In [ ]:
subs.sample()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
25876,125877,Arts,Sophomore,3.566,9.39,Summarizing_Reading,Advanced,4,False,2.4,5,Allowed_With_Citation,5,3.738,63.91,Medium

In [ ]:
subs = pd.read_csv("/ai_student_impact_dataset (1).csv")

In [ ]:
subs.value_counts()

Student_ID  Major_Category  Year_of_Study  Pre_Semester_GPA  Weekly_GenAI_Hours  Primary_Use_Case           Prompt_Engineering_Skill  Tool_Diversity  Paid_Subscription  Traditional_Study_Hours  Perceived_AI_Dependency  Institutional_Policy   Anxiety_Level_During_Exams  Post_Semester_GPA  Skill_Retention_Score  Burnout_Risk_Level
149984      Arts            Sophomore      3.245             1.42                Copywriting/Drafting       Beginner                  3               False              10.30                    3                        Actively_Encouraged    4                           3.385              85.93                  Medium                1
149983      Business        Sophomore      3.474             6.68                Direct_Answer_Generation   Intermediate              2               False              7.52                     4                        Allowed_With_Citation  9                           3.507              75.47                  Low                   1
149982      STEM            Graduate       2.256             10.89               Copywriting/Drafting       Advanced                  4               False              10.42                    1                        Allowed_With_Citation  1                           2.450              84.88                  Low                   1
149981      STEM            Graduate       3.419             25.47               Summarizing_Reading        Advanced                  4               True               14.24                    6                        Allowed_With_Citation  7                           3.879              66.16                  High                  1
149980      Business        Senior         3.750             16.00               Ideation                   Beginner                  1               True               7.00                     3                        Allowed_With_Citation  1                           4.000              66.12                  Low                   1
                                                                                                                                                                                                                                                                                                                                             ..
100005      STEM            Sophomore      3.635             9.29                Debugging/Troubleshooting  Advanced                  4               False              12.55                    4                        Allowed_With_Citation  4                           3.798              100.00                 Medium                1
100004      Business        Senior         3.789             1.82                Copywriting/Drafting       Intermediate              4               False              15.23                    2                        Allowed_With_Citation  2                           4.000              63.58                  Medium                1
100003      Business        Freshman       3.398             21.26               Summarizing_Reading        Beginner                  2               False              10.35                    5                        Strict_Ban             9                           3.499              73.93                  Medium                1
100002      Medical         Junior         3.821             1.12                Ideation                   Advanced                  5               False              16.65                    3                        Allowed_With_Citation  9                           3.696              69.39                  Low                   1
100001      Humanities      Senior         2.418             23.31               Copywriting/Drafting       Beginner                  1               True               8.13                     5                        Allowed_With_Citation  6                           2.393              86.44                  High                  1
Name: count, Length: 50000, dtype: int64

In [ ]:
subs.count()

Student_ID                    50000
Major_Category                50000
Year_of_Study                 50000
Pre_Semester_GPA              50000
Weekly_GenAI_Hours            50000
Primary_Use_Case              50000
Prompt_Engineering_Skill      50000
Tool_Diversity                50000
Paid_Subscription             50000
Traditional_Study_Hours       50000
Perceived_AI_Dependency       50000
Institutional_Policy          50000
Anxiety_Level_During_Exams    50000
Post_Semester_GPA             50000
Skill_Retention_Score         50000
Burnout_Risk_Level            50000
dtype: int64

In [ ]:
subs.sum()

Student_ID                                                           6250025000
Major_Category                HumanitiesMedicalBusinessBusinessSTEMSTEMSTEMA...
Year_of_Study                 SeniorJuniorFreshmanSeniorSophomoreJuniorFresh...
Pre_Semester_GPA                                                     157305.117
Weekly_GenAI_Hours                                                    421387.61
Primary_Use_Case              Copywriting/DraftingIdeationSummarizing_Readin...
Prompt_Engineering_Skill      BeginnerAdvancedBeginnerIntermediateAdvancedBe...
Tool_Diversity                                                           140013
Paid_Subscription                                                         21154
Traditional_Study_Hours                                               560463.55
Perceived_AI_Dependency                                                  175268
Institutional_Policy          Allowed_With_CitationAllowed_With_CitationStri...
Anxiety_Level_During_Exams                                               213538
Post_Semester_GPA                                                    167464.971
Skill_Retention_Score                                                3789906.25
Burnout_Risk_Level            HighLowMediumMediumMediumHighMediumMediumMediu...
dtype: object

In [ ]:
subs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  50000 non-null  int64
 1   Major_Category              50000 non-null  object
 2   Year_of_Study               50000 non-null  object
 3   Pre_Semester_GPA            50000 non-null  float64
 4   Weekly_GenAI_Hours          50000 non-null  float64
 5   Primary_Use_Case            50000 non-null  object
 6   Prompt_Engineering_Skill    50000 non-null  object
 7   Tool_Diversity              50000 non-null  int64
 8   Paid_Subscription           50000 non-null  bool
 9   Traditional_Study_Hours     50000 non-null  float64
 10  Perceived_AI_Dependency     50000 non-null  int64
 11  Institutional_Policy        50000 non-null  object
 12  Anxiety_Level_During_Exams  50000 non-null  int64
 13  Post_Semester_GPA           50000 non-null  float64
 14  Skill_Retention_Score       50000 non-null  float64
 15  Burnout_Risk_Level          50000 non-null  object
dtypes: bool(1), float64(5), int64(4), object(6)
memory usage: 5.8+ MB

In [ ]:
subs.mean()

TypeError: Could not convert ['HumanitiesMedicalBusinessBusinessSTEMSTEMSTEMArtsBusinessBusinessSTEMMedicalArtsSTEMSTEMSTEMHumanitiesBusinessHumanitiesSTEMBusinessSTEMSTEMHumanitiesHumanitiesArtsSTEMBusinessBusinessSTEMBusinessSTEMSTEMMedicalMedicalArtsHumanitiesSTEMBusinessHumanitiesSTEMHumanitiesSTEMMedicalSTEMBusinessHumanitiesBusinessBusinessSTEMMedicalArtsMedicalMedicalBusinessMedicalSTEMSTEMSTEMHumanitiesHumanitiesSTEMArtsHumanitiesSTEMBusinessSTEMArtsSTEMMedicalArtsSTEMSTEMArtsBusinessBusinessArtsSTEMHumanitiesSTEMArtsBusinessHumanitiesSTEMHumanitiesHumanitiesBusinessBusinessMedicalHumanitiesSTEMBusinessArtsBusinessArtsHumanitiesBusinessHumanitiesSTEMSTEMSTEMBusinessHumanitiesBusinessMedicalSTEMHumanitiesArtsSTEMSTEMSTEMSTEMMedicalArtsBusinessMedicalArtsSTEMMedicalBusinessArtsMedicalHumanitiesSTEMSTEMHumanitiesArtsArtsSTEMBusinessHumanitiesSTEMSTEMHumanitiesMedicalHumanitiesBusinessBusinessHumanitiesMedicalMedicalSTEMHumanitiesHumanitiesSTEMSTEMBusinessBusinessSTEMSTEMMedicalSTEMSTEMHumanitiesMedicalSTEMBusinessArtsSTEMBusinessHumanitiesBusinessBusinessBusinessSTEMArtsHumanitiesSTEMSTEMBusinessBusinessSTEMBusinessSTEMBusinessSTEMBusinessHumanitiesMedicalSTEMHumanitiesSTEMMedicalMedicalSTEMBusinessArtsBusinessBusinessSTEMSTEMMedicalMedicalBusinessHumanitiesHumanitiesBusinessMedicalMedicalArtsBusinessSTEMSTEMMedicalBusinessSTEMSTEMBusinessSTEMSTEMBusinessBusinessBusinessSTEMBusinessSTEMHumanitiesBusinessBusinessArtsBusinessBusinessSTEMHumanitiesSTEMSTEMMedicalHumanitiesMedicalBusinessArtsBusinessBusinessHumanitiesSTEMBusinessSTEMSTEMBusinessSTEMMedicalMedicalMedicalHumanitiesSTEMMedicalHumanitiesMedicalMedicalArtsSTEMHumanitiesArtsHumanitiesSTEMBusinessMedicalBusinessBusinessSTEMBusinessMedicalSTEMBusinessMedicalBusinessBusinessBusinessHumanitiesSTEMArtsArtsArtsMedicalBusinessBusinessArtsBusinessBusinessArtsMedicalHumanitiesHumanitiesSTEMBusinessSTEMHumanitiesBusinessSTEMBusinessSTEMSTEMArtsHumanitiesSTEMBusinessArtsSTEMBusinessSTEMSTEMBusinessBusinessBusinessBusinessMedicalBusinessHumanitiesArtsSTEMHumanitiesSTEMSTEMMedicalArtsBusinessHumanitiesSTEMSTEMSTEMBusinessBusinessBusinessSTEMMedicalBusinessBusinessBusinessHumanitiesSTEMHumanitiesArtsSTEMSTEMSTEMSTEMArtsBusinessHumanitiesSTEMHumanitiesHumanitiesSTEMHumanitiesHumanitiesBusinessBusinessSTEMHumanitiesBusinessBusinessArtsBusinessSTEMSTEMBusinessSTEMBusinessMedicalBusinessHumanitiesBusinessHumanitiesBusinessMedicalHumanitiesMedicalMedicalSTEMSTEMSTEMSTEMSTEMBusinessSTEMHumanitiesArtsSTEMArtsSTEMSTEMBusinessBusinessMedicalBusinessArtsSTEMSTEMArtsArtsMedicalHumanitiesHumanitiesArtsHumanitiesMedicalArtsHumanitiesArtsArtsSTEMMedicalBusinessArtsHumanitiesMedicalHumanitiesSTEMMedicalSTEMHumanitiesMedicalMedicalBusinessBusinessHumanitiesSTEMHumanitiesBusinessArtsArtsArtsSTEMHumanitiesSTEMBusinessHumanitiesMedicalHumanitiesSTEMSTEMArtsBusinessSTEMSTEMBusinessSTEMArtsBusinessSTEMSTEMMedicalHumanitiesHumanitiesArtsMedicalMedicalArtsHumanitiesSTEMArtsBusinessHumanitiesMedicalSTEMHumanitiesSTEMHumanitiesSTEMSTEMSTEMBusinessBusinessBusinessMedicalHumanitiesSTEMArtsSTEMMedicalSTEMMedicalSTEMMedicalBusinessMedicalSTEMBusinessMedicalBusinessBusinessBusinessHumanitiesBusinessBusinessMedicalSTEMSTEMMedicalMedicalHumanitiesBusinessSTEMSTEMHumanitiesHumanitiesBusinessSTEMMedicalMedicalBusinessBusinessHumanitiesArtsBusinessSTEMMedicalArtsMedicalBusinessBusinessHumanitiesMedicalArtsSTEMSTEMHumanitiesArtsMedicalSTEMBusinessHumanitiesMedicalArtsArtsHumanitiesHumanitiesSTEMSTEMArtsArtsMedicalMedicalBusinessArtsMedicalArtsSTEMHumanitiesSTEMMedicalBusinessSTEMBusinessBusinessHumanitiesSTEMBusinessBusinessArtsBusinessArtsBusinessBusinessMedicalHumanitiesSTEMSTEMArtsBusinessBusinessSTEMSTEMSTEMHumanitiesBusinessHumanitiesHumanitiesMedicalHumanitiesBusinessArtsHumanitiesBusinessArtsMedicalSTEMMedicalHumanitiesSTEMHumanitiesMedicalHumanitiesHumanitiesBusinessSTEMSTEMSTEMSTEMSTEMSTEMBusinessSTEMHumanitiesMedicalHumanitiesBusinessSTEMSTEMSTEMSTEMSTEMSTEMSTEMSTEMHumanitiesSTEMHumanitiesBusinessBusinessSTEMArtsBusinessSTEMMedicalMedicalSTEMSTEMArtsBusinessSTEMSTEMHumanitiesHumanitiesBusinessHumanitiesHumanitiesBusinessSTEMSTEMBusinessMedicalBusinessBusinessSTEMHumanitiesBusinessSTEMSTEMHumanitiesSTEMHumanitiesSTEMHumanitiesSTEMMedicalBusinessBusinessArtsHumanitiesSTEMBusinessBusinessBusinessHumanitiesSTEMSTEMHumanitiesBusinessBusinessHumanitiesMedicalBusinessSTEMSTEMSTEMSTEMSTEMSTEMSTEMSTEMMedicalSTEMBusinessHumanitiesMedicalSTEMHumanitiesMedicalArtsArtsSTEMSTEMBusinessMedicalBusinessBusinessSTEMArtsSTEMHumanitiesHumanitiesBusinessSTEMSTEMBusinessSTEMBusinessSTEMHumanitiesBusinessSTEMHumanitiesSTEMSTEMMedicalHumanitiesArtsSTEMBusinessArtsBusinessHumanitiesHumanitiesHumanitiesMedicalArtsMedicalSTEMBusinessMedicalSTEMSTEMBusinessBusinessArtsSTEMArtsSTEMSTEMSTEMArtsBusinessBusinessHumanitiesMedicalHumanitiesArtsHumanitiesHumanitiesHumanitiesHumanitiesBusinessBusinessSTEMMedicalHumanitiesBusinessMedicalBusinessSTEMMedicalBusinessHumanitiesSTEMArtsBusinessBusinessMedicalArtsSTEMHumanitiesSTEMBusinessSTEMBusinessArtsMedicalHumanitiesArtsSTEMArtsSTEMHumanitiesArtsSTEMSTEMBusinessBusinessBusinessBusinessBusinessSTEMHumanitiesSTEMMedicalBusinessHumanitiesHumanitiesMedicalSTEMBusinessBusinessBusinessSTEMMedicalMedicalBusinessBusinessMedicalBusinessSTEMBusinessBusinessHumanitiesBusinessMedicalMedicalHumanitiesSTEMMedicalArtsSTEMMedicalArtsBusinessBusinessHumanitiesSTEMHumanitiesArtsSTEMHumanitiesHumanitiesBusinessMedicalHumanitiesHumanitiesBusinessHumanitiesSTEMHumanitiesSTEMSTEMHumanitiesHumanitiesMedicalHumanitiesBusinessBusinessSTEMBusinessSTEMMedicalSTEMHumanitiesSTEMMedicalBusinessBusinessSTEMBusinessSTEMMedicalSTEMSTEMSTEMHumanitiesBusinessSTEMArtsHumanitiesBusinessHumanitiesHumanitiesBusinessSTEMSTEMArtsMedicalHumanitiesSTEMBusinessHumanitiesSTEMSTEMBusinessBusinessSTEMSTEMSTEMBusinessSTEMSTEMArtsSTEMBusinessSTEMSTEMSTEMBusinessArtsArtsHumanitiesBusinessSTEMSTEMMedicalSTEMSTEMSTEMSTEMSTEMBusinessHumanitiesMedicalArtsHumanitiesSTEMHumanitiesBusinessSTEMBusinessHumanitiesBusinessHumanitiesSTEMMedicalArtsSTEMArtsHumanitiesMedicalArtsHumanitiesSTEMSTEMBusinessBusinessSTEMSTEMArtsMedicalBusinessSTEMSTEMSTEMMedicalSTEMBusinessSTEMBusinessBusinessArtsSTEMSTEMSTEMMedicalMedicalBusinessBusinessBusinessSTEMMedicalHumanitiesHumanitiesBusinessSTEMSTEMBusinessSTEMBusinessSTEMHumanitiesSTEMHumanitiesBusinessSTEMBusinessHumanitiesBusinessMedicalBusinessSTEMSTEMSTEMBusinessSTEMHumanitiesBusinessHumanitiesArtsSTEMSTEMBusinessHumanitiesBusinessHumanitiesSTEMArtsArtsBusinessSTEMBusinessHumanitiesSTEMMedicalSTEMMedicalHumanitiesSTEMBusinessMedicalBusinessArtsBusinessBusinessArtsSTEMHumanitiesSTEMMedicalMedicalSTEMBusinessMedicalSTEMBusinessMedicalSTEMBusinessSTEMMedicalMedicalMedicalHumanitiesArtsArtsHumanitiesArtsSTEMBusinessSTEMSTEMSTEMBusinessHumanitiesBusinessSTEMHumanitiesBusinessArtsHumanitiesBusinessMedicalBusinessSTEMSTEMMedicalSTEMMedicalBusinessMedicalArtsMedicalHumanitiesArtsHumanitiesHumanitiesBusinessMedicalMedicalArtsHumanitiesHumanitiesBusinessSTEMSTEMHumanitiesSTEMSTEMSTEMSTEMSTEMMedicalHumanitiesHumanitiesBusinessSTEMMedicalArtsSTEMHumanitiesMedicalMedicalHumanitiesBusinessSTEMMedicalSTEMMedicalBusinessBusinessBusinessSTEMSTEMSTEMSTEMArtsHumanitiesSTEMMedicalMedicalMedicalMedicalSTEMHumanitiesArtsBusinessSTEMArtsSTEMSTEMBusinessBusinessBusinessSTEMMedicalSTEMSTEMMedicalMedicalArtsArtsBusinessBusinessSTEMHumanitiesHumanitiesSTEMBusinessHumanitiesSTEMSTEMBusinessSTEMArtsHumanitiesHumanitiesBusinessArtsHumanitiesBusinessBusinessSTEMMedicalArtsBusinessArtsArtsBusinessArtsBusinessBusinessBusinessArtsSTEMMedicalMedicalSTEMArtsSTEMHumanitiesBusinessSTEMArtsArtsBusinessSTEMSTEMBusinessMedicalBusinessSTEMBusinessBusinessArtsSTEMArtsBusinessMedicalHumanitiesBusinessMedicalSTEMMedicalBusinessSTEMHumanitiesBusinessSTEMBusinessHumanitiesBusinessSTEMMedicalMedicalMedicalBusinessSTEMArtsSTEMSTEMHumanitiesHumanitiesArtsBusinessHumanitiesSTEMMedicalHumanitiesHumanitiesSTEMArtsBusinessSTEMSTEMBusinessBusinessSTEMMedicalSTEMHumanitiesMedicalHumanitiesBusinessHumanitiesSTEMMedicalHumanitiesMedicalSTEMSTEMSTEMBusinessHumanitiesArtsHumanitiesMedicalSTEMArtsArtsArtsArtsArtsBusinessSTEMSTEMMedicalBusinessArtsHumanitiesSTEMSTEMBusinessHumanitiesSTEMHumanitiesSTEMBusinessSTEMArtsHumanitiesHumanitiesSTEMSTEMHumanitiesHumanitiesBusinessSTEMBusinessArtsArtsSTEMHumanitiesSTEMSTEMMedicalSTEMHumanitiesBusinessBusinessBusinessSTEMHumanitiesBusinessSTEMHumanitiesSTEMSTEMHumanitiesSTEMBusinessBusinessArtsSTEMSTEMSTEMBusinessBusinessSTEMMedicalSTEMBusinessBusinessMedicalBusinessArtsHumanitiesArtsSTEMMedicalBusinessArtsHumanitiesBusinessBusinessBusinessSTEMSTEMSTEMSTEMMedicalSTEMMedicalHumanitiesSTEMArtsBusinessHumanitiesBusinessBusinessSTEMMedicalMedicalBusinessSTEMBusinessSTEMSTEMSTEMHumanitiesArtsBusinessBusinessHumanitiesHumanitiesHumanitiesMedicalSTEMArtsBusinessHumanitiesBusinessHumanitiesMedicalMedicalHumanitiesSTEMBusinessMedicalSTEMBusinessBusinessBusinessSTEMBusinessMedicalSTEMSTEMMedicalSTEMArtsHumanitiesSTEMMedicalHumanitiesBusinessHumanitiesBusinessSTEMHumanitiesMedicalSTEMBusinessHumanitiesArtsSTEMMedicalHumanitiesSTEMSTEMSTEMBusinessHumanitiesArtsHumanitiesSTEMBusinessBusinessSTEMSTEMSTEMBusinessBusinessHumanitiesArtsArtsBusinessArtsSTEMSTEMSTEMSTEMBusinessMedicalSTEMSTEMHumanitiesMedicalHumanitiesBusinessSTEMSTEMMedicalMedicalSTEMMedicalBusinessArtsHumanitiesBusinessHumanitiesBusinessSTEMSTEMHumanitiesBusinessSTEMBusinessMedicalSTEMBusinessHumanitiesArtsSTEMBusinessArtsMedicalBusinessHumanitiesBusinessArtsBusinessSTEMMedicalBusinessBusinessSTEMBusinessHumanitiesBusinessSTEMBusinessMedicalSTEMMedicalHumanitiesMedicalArtsBusinessBusinessMedicalHumanitiesHumanitiesBusinessArtsArtsArtsHumanitiesArtsSTEMBusinessSTEMHumanitiesHumanitiesHumanitiesBusinessHumanitiesHumanitiesSTEMHumanitiesSTEMSTEMBusinessBusinessBusinessHumanitiesHumanitiesArtsBusinessHumanitiesSTEMHumanitiesHumanitiesHumanitiesBusinessBusinessBusinessArtsArtsBusinessMedicalSTEMSTEMSTEMBusinessMedicalSTEMMedicalSTEMMedicalHumanitiesSTEMHumanitiesSTEMSTEMHumanitiesArtsBusinessHumanitiesBusinessBusinessSTEMHumanitiesSTEMSTEMBusinessSTEMBusinessBusinessSTEMBusinessSTEMMedicalHumanitiesArtsBusinessSTEMBusinessMedicalBusinessArtsMedicalSTEMSTEMBusinessHumanitiesArtsMedicalHumanitiesSTEMArtsSTEMArtsHumanitiesBusinessSTEMBusinessHumanitiesBusinessSTEMBusinessArtsSTEMSTEMSTEMBusinessBusinessBusinessSTEMHumanitiesBusinessHumanitiesMedicalSTEMBusinessHumanitiesHumanitiesBusinessBusinessMedicalSTEMSTEMBusinessBusinessSTEMSTEMSTEMMedicalSTEMHumanitiesSTEMHumanitiesSTEMBusinessSTEMArtsSTEMBusinessMedicalBusinessBusinessHumanitiesHumanitiesBusinessMedicalBusinessBusinessBusinessHumanitiesSTEMBusinessMedicalSTEMBusinessSTEMBusinessSTEMHumanitiesArtsHumanitiesBusinessArtsMedicalSTEMHumanitiesSTEMMedicalMedicalBusinessArtsBusinessBusinessSTEMArtsSTEMArtsArtsBusinessSTEMHumanitiesSTEMHumanitiesSTEMMedicalBusinessHumanitiesHumanitiesHumanitiesBusinessBusinessMedicalHumanitiesMedicalArtsSTEMMedicalSTEMArtsHumanitiesMedicalArtsArtsArtsHumanitiesSTEMHumanitiesSTEMBusinessHumanitiesMedicalBusinessArtsSTEMArtsMedicalHumanitiesBusinessArtsSTEMBusinessHumanitiesSTEMHumanitiesSTEMSTEMSTEMMedicalBusinessMedicalHumanitiesHumanitiesBusinessHumanitiesSTEMBusinessSTEMBusinessBusinessSTEMSTEMArtsHumanitiesSTEMMedicalSTEMBusinessMedicalSTEMSTEMSTEMHumanitiesSTEMBusinessSTEMBusinessMedicalArtsBusinessHumanitiesBusinessBusinessHumanitiesSTEMMedicalHumanitiesSTEMHumanitiesHumanitiesArtsBusinessArtsSTEMHumanitiesHumanitiesSTEMSTEMArtsSTEMBusinessSTEMSTEMSTEMMedicalArtsMedicalHumanitiesSTEMBusinessHumanitiesArtsSTEMHumanitiesSTEMHumanitiesBusinessHumanitiesHumanitiesHumanitiesHumanitiesArtsMedicalMedicalArtsHumanitiesBusinessHumanitiesSTEMArtsSTEMMedicalHumanitiesBusinessBusinessMedicalBusinessBusinessSTEMBusinessSTEMBusinessBusinessBusinessSTEMSTEMBusinessSTEMSTEMSTEMMedicalBusinessHumanitiesSTEMHumanitiesArtsBusinessSTEMSTEMSTEMBusinessArtsSTEMSTEMSTEMMedicalSTEMArtsBusinessHumanitiesSTEMSTEMBusinessArtsBusinessBusinessSTEMMedicalArtsSTEMMedicalBusinessBusinessBusinessArtsBusinessSTEMHumanitiesMedicalSTEMHumanitiesHumanitiesHumanitiesBusinessMedicalSTEMSTEMSTEMMedicalBusinessSTEMArtsArtsArtsMedicalSTEMArtsHumanitiesArtsBusinessArtsBusinessSTEMBusinessMedicalMedicalSTEMSTEMSTEMBusinessArtsSTEMBusinessArtsBusinessBusinessBusinessBusinessSTEMBusinessBusinessMedicalBusinessArtsSTEMHumanitiesSTEMSTEMBusinessMedicalSTEMHumanitiesArtsSTEMBusinessBusinessBusinessSTEMHumanitiesArtsBusinessSTEMArtsSTEMBusinessSTEMMedicalHumanitiesHumanitiesSTEMHumanitiesMedicalMedicalHumanitiesHumanitiesBusinessMedicalBusinessHumanitiesHumanitiesBusinessSTEMBusinessHumanitiesArtsSTEMBusinessHumanitiesBusinessSTEMBusinessBusinessBusinessBusinessBusinessArtsSTEMArtsHumanitiesSTEMSTEMHumanitiesArtsBusinessArtsBusinessHumanitiesSTEMHumanitiesHumanitiesSTEMSTEMBusinessBusinessMedicalMedicalBusinessHumanitiesBusinessArtsSTEMHumanitiesArtsHumanitiesBusinessBusinessSTEMHumanitiesHumanitiesSTEMSTEMArtsSTEMBusinessSTEMMedicalSTEMHumanitiesMedicalArtsSTEMArtsHumanitiesHumanitiesSTEMSTEMBusinessHumanitiesHumanitiesBusinessArtsSTEMBusinessSTEMArtsBusinessMedicalSTEMSTEMSTEMSTEMSTEMMedicalSTEMSTEMArtsHumanitiesArtsSTEMHumanitiesSTEMSTEMMedicalSTEMBusinessHumanitiesHumanitiesMedicalSTEMBusinessMedicalBusinessMedicalSTEMHumanitiesSTEMBusinessMedicalSTEMBusinessSTEMBusinessHumanitiesMedicalBusinessHumanitiesSTEMSTEMSTEMSTEMArtsBusinessBusinessSTEMArtsBusinessSTEMBusinessBusinessSTEMHumanitiesHumanitiesSTEMMedicalArtsBusinessHumanitiesHumanitiesBusinessBusinessSTEMBusinessArtsHumanitiesSTEMArtsSTEMSTEMSTEMHumanitiesArtsBusinessSTEMMedicalMedicalMedicalSTEMHumanitiesMedicalArtsSTEMSTEMHumanitiesMedicalBusinessHumanitiesSTEMBusinessArtsHumanitiesArtsMedicalSTEMBusinessSTEMArtsBusinessBusinessArtsHumanitiesMedicalBusinessSTEMBusinessArtsHumanitiesArtsMedicalSTEMMedicalSTEMSTEMSTEMMedicalBusinessSTEMHumanitiesBusinessSTEMMedicalArtsBusinessMedicalHumanitiesMedicalBusinessBusinessSTEMMedicalHumanitiesSTEMSTEMBusinessBusinessBusinessMedicalSTEMBusinessSTEMArtsArtsBusinessBusinessHumanitiesHumanitiesArtsHumanitiesHumanitiesHumanitiesArtsHumanitiesSTEMBusinessArtsSTEMSTEMSTEMHumanitiesHumanitiesBusinessBusinessBusinessHumanitiesArtsHumanitiesMedicalBusinessSTEMBusinessHumanitiesBusinessSTEMSTEMArtsSTEMArtsSTEMBusinessBusinessBusinessHumanitiesSTEMSTEMHumanitiesBusinessMedicalMedicalArtsArtsBusinessSTEMMedicalBusinessBusinessSTEMHumanitiesHumanitiesArtsBusinessHumanitiesMedicalSTEMHumanitiesSTEMBusinessMedicalSTEMArtsSTEMMedicalArtsArtsSTEMMedicalBusinessHumanitiesArtsSTEMMedicalSTEMBusinessBusinessSTEMSTEMSTEMHumanitiesHumanitiesBusinessSTEMSTEMBusinessSTEMMedicalArtsBusinessBusinessMedicalSTEMSTEMSTEMArtsSTEMBusinessMedicalArtsBusinessSTEMArtsBusinessSTEMSTEMMedicalBusinessArtsMedicalBusinessBusinessHumanitiesHumanitiesHumanitiesArtsBusinessMedicalHumanitiesBusinessBusinessBusinessBusinessSTEMBusinessSTEMHumanitiesHumanitiesBusinessMedicalBusinessBusinessBusinessBusinessSTEMSTEMHumanitiesHumanitiesSTEMSTEMSTEMMedicalHumanitiesHumanitiesSTEMBusinessSTEMSTEMBusinessSTEMSTEMSTEMSTEMSTEMHumanitiesArtsBusinessBusinessSTEMMedicalHumanitiesSTEMBusinessSTEMHumanitiesBusinessMedicalHumanitiesBusinessMedicalSTEMSTEMHumanitiesHumanitiesHumanitiesMedicalBusinessBusinessHumanitiesArtsMedicalArtsSTEMBusinessSTEMSTEMSTEMBusinessBusinessSTEMHumanitiesHumanitiesHumanitiesSTEMHumanitiesArtsSTEMSTEMHumanitiesMedicalBusinessBusinessHumanitiesBusinessSTEMBusinessMedicalBusinessMedicalBusinessSTEMMedicalSTEMBusinessSTEMSTEMHumanitiesSTEMHumanitiesBusinessSTEMSTEMBusinessHumanitiesBusinessBusinessArtsBusinessHumanitiesBusinessSTEMHumanitiesArtsHumanitiesArtsArtsArtsMedicalHumanitiesHumanitiesBusinessHumanitiesBusinessBusinessBusinessHumanitiesSTEMHumanitiesSTEMMedicalHumanitiesSTEMSTEMBusinessBusinessHumanitiesSTEMHumanitiesHumanitiesBusinessBusinessHumanitiesSTEMMedicalHumanitiesBusinessSTEMHumanitiesSTEMBusinessMedicalHumanitiesSTEMSTEMHumanitiesSTEMSTEMArtsHumanitiesSTEMMedicalSTEMMedicalHumanitiesMedicalBusinessArtsMedicalSTEMMedicalHumanitiesHumanitiesHumanitiesBusinessSTEMBusinessBusinessArtsArtsHumanitiesHumanitiesSTEMSTEMSTEMHumanitiesSTEMMedicalBusinessHumanitiesBusinessSTEMHumanitiesBusinessHumanitiesHumanitiesMedicalMedicalBusinessBusinessBusinessSTEMHumanitiesSTEMHumanitiesBusinessSTEMMedicalMedicalBusinessBusinessArtsSTEMArtsSTEMArtsSTEMMedicalMedicalSTEMHumanitiesMedicalHumanitiesArtsBusinessHumanitiesSTEMSTEMArtsHumanitiesBusinessHumanitiesBusinessArtsMedicalHumanitiesArtsArtsBusinessMedicalSTEMSTEMArtsHumanitiesArtsMedicalSTEMMedicalHumanitiesBusinessBusinessMedicalSTEMHumanitiesBusinessBusinessBusinessSTEMSTEMHumanitiesArtsSTEMSTEMMedicalSTEMMedicalBusinessArtsSTEMSTEMBusinessArtsBusinessSTEMArtsArtsBusinessArtsArtsBusinessSTEMHumanitiesSTEMHumanitiesHumanitiesSTEMHumanitiesSTEMArtsMedicalSTEMMedicalBusinessSTEMSTEMBusinessArtsBusinessSTEMSTEMHumanitiesSTEMSTEMSTEMArtsMedicalHumanitiesMedicalHumanitiesHumanitiesSTEMBusinessMedicalBusinessHumanitiesBusinessSTEMMedicalBusinessHumanitiesBusinessBusinessSTEMBusinessSTEMBusinessArtsArtsBusinessBusinessSTEMArtsSTEMHumanitiesSTEMSTEMBusinessSTEMBusinessHumanitiesSTEMBusinessSTEMSTEMBusinessSTEMArtsSTEMSTEMBusinessHumanitiesSTEMHumanitiesSTEMArtsHumanitiesArtsMedicalHumanitiesMedicalHumanitiesMedicalSTEMBusinessHumanitiesHumanitiesBusinessBusinessSTEMSTEMBusinessBusinessMedicalArtsMedicalBusinessSTEMSTEMArtsBusinessSTEMHumanitiesMedicalBusinessHumanitiesHumanitiesSTEMHumanitiesHumanitiesSTEMArtsHumanitiesArtsArtsSTEMBusinessHumanitiesMedicalSTEMBusinessBusinessSTEMSTEMBusinessBusinessHumanitiesBusinessHumanitiesBusinessSTEMMedicalSTEMHumanitiesSTEMSTEMBusinessSTEMArtsSTEMHumanitiesHumanitiesSTEMSTEMHumanitiesHumanitiesHumanitiesBusinessBusinessSTEMHumanitiesMedicalBusinessBusinessHumanitiesArtsArtsBusinessMedicalSTEMSTEMArtsArtsSTEMSTEMSTEMSTEMArtsBusinessHumanitiesHumanitiesSTEMSTEMBusinessMedicalArtsSTEMMedicalArtsArtsHumanitiesHumanitiesHumanitiesSTEMSTEMSTEMHumanitiesBusinessHumanitiesSTEMMedicalMedicalArtsMedicalBusinessMedicalSTEMHumanitiesSTEMSTEMSTEMBusinessArtsBusinessSTEMArtsBusinessHumanitiesBusinessSTEMHumanitiesMedicalSTEMHumanitiesMedicalBusinessSTEMSTEMSTEMBusinessHumanitiesSTEMMedicalBusinessSTEMBusinessBusinessSTEMSTEMArtsHumanitiesBusinessHumanitiesSTEMSTEMHumanitiesSTEMSTEMArtsMedicalArtsArtsSTEMMedicalSTEMMedicalMedicalBusinessMedicalBusinessSTEMHumanitiesBusinessSTEMBusinessMedicalSTEMArtsMedicalMedicalMedicalBusinessMedicalArtsSTEMHumanitiesBusinessSTEMBusinessBusinessSTEMBusinessArtsHumanitiesSTEMSTEMHumanitiesMedicalSTEMBusinessSTEMHumanitiesArtsBusinessSTEMHumanitiesSTEMHumanitiesBusinessSTEMSTEMHumanitiesMedicalMedicalSTEMArtsHumanitiesHumanitiesArtsMedicalMedicalBusinessHumanitiesArtsSTEMBusinessHumanitiesBusinessSTEMSTEMMedicalSTEMBusinessSTEMSTEMSTEMSTEMArtsSTEMMedicalBusinessHumanitiesBusinessBusinessArtsSTEMHumanitiesMedicalMedicalMedicalHumanitiesArtsHumanitiesHumanitiesSTEMBusinessSTEMHumanitiesArtsSTEMSTEMSTEMMedicalBusinessHumanitiesArtsArtsHumanitiesBusinessArtsBusinessSTEMMedicalBusinessSTEMHumanitiesSTEMSTEMArtsSTEMHumanitiesBusinessSTEMMedicalSTEMHumanitiesHumanitiesSTEMSTEMBusinessMedicalSTEMBusinessBusinessArtsHumanitiesHumanitiesHumanitiesBusinessArtsSTEMHumanitiesMedicalArtsMedicalArtsHumanitiesBusinessBusinessSTEMBusinessBusinessSTEMArtsBusinessMedicalSTEMSTEMBusinessSTEMBusinessArtsSTEMBusinessBusinessHumanitiesMedicalArtsBusinessBusinessHumanitiesMedicalBusinessBusinessArtsSTEMArtsSTEMHumanitiesHumanitiesMedicalArtsBusinessBusinessBusinessMedicalHumanitiesHumanitiesSTEMArtsBusinessHumanitiesSTEMArtsSTEMBusinessMedicalHumanitiesSTEMBusinessArtsBusinessMedicalSTEMBusinessBusinessArtsSTEMArtsBusinessHumanitiesSTEMArtsSTEMHumanitiesSTEMMedicalBusinessArtsSTEMBusinessBusinessArtsMedicalSTEMBusinessSTEMBusinessSTEMHumanitiesHumanitiesBusinessHumanitiesBusinessHumanitiesSTEMArtsSTEMHumanitiesBusinessHumanitiesSTEMHumanitiesMedicalBusinessBusinessBusinessSTEMHumanitiesArtsSTEMSTEMSTEMHumanitiesMedicalSTEMBusinessSTEMMedicalSTEMHumanitiesBusinessBusinessHumanitiesHumaniti

In [ ]:
subs.mode()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,STEM,Junior,3.433,40.0,Debugging/Troubleshooting,Beginner,3.0,False,1.0,3.0,Allowed_With_Citation,4.0,4.0,100.0,Medium
1,100002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,100003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,100004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,100005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,149996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49996,149997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49997,149998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49998,149999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49999,150000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
subs.median(numeric_only=True)

Student_ID                    125000.500
Pre_Semester_GPA                   3.210
Weekly_GenAI_Hours                 5.800
Tool_Diversity                     3.000
Paid_Subscription                  0.000
Traditional_Study_Hours           11.180
Perceived_AI_Dependency            3.000
Anxiety_Level_During_Exams         4.000
Post_Semester_GPA                  3.421
Skill_Retention_Score             76.000
dtype: float64

In [ ]:
subs.describe()

,Student_ID,Pre_Semester_GPA,Weekly_GenAI_Hours,Tool_Diversity,Traditional_Study_Hours,Perceived_AI_Dependency,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score
count,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,125000.500000,3.146102,8.427752,2.80026,11.209271,3.505360,4.270760,3.349299,75.798125
std,14433.901067,0.478854,8.269490,1.18802,5.156426,1.820812,2.144066,0.495673,13.281626
min,100001.000000,1.183000,0.000000,1.00000,1.000000,1.000000,1.000000,1.000000,10.780000
25%,112500.750000,2.834000,2.390000,2.00000,7.560000,2.000000,3.000000,3.023750,66.820000
50%,125000.500000,3.210000,5.800000,3.00000,11.180000,3.000000,4.000000,3.421000,76.000000
75%,137500.250000,3.521000,11.720000,4.00000,14.710000,5.000000,6.000000,3.749000,85.190000
max,150000.000000,3.998000,40.000000,5.00000,35.860000,10.000000,10.000000,4.000000,100.000000

In [ ]:
subs.iloc[-1]

Student_ID                                   150000
Major_Category                                 Arts
Year_of_Study                             Sophomore
Pre_Semester_GPA                              3.242
Weekly_GenAI_Hours                              3.3
Primary_Use_Case               Copywriting/Drafting
Prompt_Engineering_Skill                   Beginner
Tool_Diversity                                    1
Paid_Subscription                             False
Traditional_Study_Hours                        3.93
Perceived_AI_Dependency                           2
Institutional_Policy          Allowed_With_Citation
Anxiety_Level_During_Exams                        6
Post_Semester_GPA                             3.261
Skill_Retention_Score                         76.16
Burnout_Risk_Level                              Low
Name: 49999, dtype: object

In [ ]:
subs[5:15]

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
5,100006,STEM,Junior,3.449,6.50,Debugging/Troubleshooting,Beginner,1,False,14.19,4,Allowed_With_Citation,5,3.666,65.92,High
6,100007,STEM,Freshman,3.622,31.41,Summarizing_Reading,Advanced,5,True,13.11,8,Allowed_With_Citation,7,4.000,67.97,Medium
7,100008,Arts,Junior,2.746,5.33,Copywriting/Drafting,Intermediate,3,False,18.45,2,Actively_Encouraged,1,2.965,85.09,Medium
8,100009,Business,Sophomore,3.420,2.00,Debugging/Troubleshooting,Beginner,2,True,2.87,1,Strict_Ban,5,3.396,55.71,Medium
9,100010,Business,Sophomore,3.046,19.99,Debugging/Troubleshooting,Intermediate,2,True,12.49,3,Strict_Ban,8,2.978,87.18,High
10,100011,STEM,Graduate,3.407,5.16,Summarizing_Reading,Advanced,3,False,11.43,5,Allowed_With_Citation,3,3.617,95.42,High
11,100012,Medical,Junior,2.627,3.62,Direct_Answer_Generation,Intermediate,3,False,8.05,3,Actively_Encouraged,3,2.699,72.41,Medium
12,100013,Arts,Senior,3.479,2.86,Copywriting/Drafting,Beginner,2,False,8.95,2,Actively_Encouraged,4,3.612,67.68,High
13,100014,STEM,Junior,3.225,8.95,Direct_Answer_Generation,Beginner,1,False,25.30,2,Allowed_With_Citation,3,3.935,64.47,Medium
14,100015,STEM,Freshman,3.202,1.22,Copywriting/Drafting,Beginner,1,False,16.52,2,Allowed_With_Citation,4,3.122,70.70,Low

In [ ]:
subs[-5:]

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
49995,149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
49996,149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
49997,149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
49998,149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium
49999,150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low

In [ ]:
subs[::2]

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
6,100007,STEM,Freshman,3.622,31.41,Summarizing_Reading,Advanced,5,True,13.11,8,Allowed_With_Citation,7,4.000,67.97,Medium
8,100009,Business,Sophomore,3.420,2.00,Debugging/Troubleshooting,Beginner,2,True,2.87,1,Strict_Ban,5,3.396,55.71,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49990,149991,Business,Senior,2.970,2.63,Summarizing_Reading,Intermediate,2,False,24.95,1,Allowed_With_Citation,1,3.238,84.87,Medium
49992,149993,Business,Graduate,2.829,2.59,Debugging/Troubleshooting,Advanced,3,True,7.54,1,Allowed_With_Citation,4,3.176,84.04,Low
49994,149995,Humanities,Senior,3.556,15.19,Summarizing_Reading,Advanced,4,True,1.00,3,Actively_Encouraged,5,3.788,74.76,High
49996,149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
49998,149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium

In [ ]:
subs.loc[[3,4,5]]

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
5,100006,STEM,Junior,3.449,6.50,Debugging/Troubleshooting,Beginner,1,False,14.19,4,Allowed_With_Citation,5,3.666,65.92,High

In [ ]:
subs_series = subs['Student_ID']
subs_series[1] = 100
subs_series

/tmp/ipykernel_586/2505657200.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subs_series[1] = 100

0        100001
1           100
2        100003
3        100004
4        100005
          ...
49995    149996
49996    149997
49997    149998
49998    149999
49999    150000
Name: Student_ID, Length: 50000, dtype: int64

In [ ]:
subs_series[1]

In [ ]:
subs_series['Prompt_Engineering_Skill'] =100

/tmp/ipykernel_586/2117723769.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subs_series['Prompt_Engineering_Skill'] =100

In [ ]:
subs_ser[2:4] = [100,100]
subs_ser

In [ ]:
subs[2:5] =100
subs

/tmp/ipykernel_586/3142550873.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '100' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  subs[2:5] =100

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100,100,100,100.000,100.00,100,100,100,100,100.00,100,100,100,100.000,100.00,100
3,100,100,100,100.000,100.00,100,100,100,100,100.00,100,100,100,100.000,100.00,100
4,100,100,100,100.000,100.00,100,100,100,100,100.00,100,100,100,100.000,100.00,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
49996,149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
49997,149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
49998,149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium
49999,150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low